services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - python-runtime
      - node-runtime
      - ruby-runtime

  python-runtime:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
    volumes:
      - ./runtime-volumes/python:/workspace
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 128m
    cpus: 0.5

  node-runtime:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    volumes:
      - ./runtime-volumes/node:/workspace
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 128m
    cpus: 0.5

  ruby-runtime:
    build:
      context: .
      dockerfile: docker/ruby.Dockerfile
    volumes:
      - ./runtime-volumes/ruby:/workspace
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 128m
    cpus: 0.5
