services:
  frontend:
    image: crashcourse:latest
    container_name: crashcourse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  caddy_data:
  caddy_config:
